# Configuration file for the AdminLTE bundle
#
# For more information about the bundle settings visit:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/configurations.md
#
# For tabs in the control_sidebar (right screen) add the 'control_sidebar' config key:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/control_sidebar.md
#

admin_lte:
    options:
        default_avatar: bundles/adminlte/images/default_avatar.png
        fixed_layout: false
        boxed_layout: true
        collapsed_sidebar: false
        mini_sidebar: true
        skin: skin-yellow
        #max_navbar_notifications: 10
        #max_navbar_tasks: 10
        #max_navbar_messages: 10

    #    theme:
    #        widget:
    #            type: warning
    #            bordered: true
    #            collapsible: true
    #            collapsible_title: 'Collapse'
    #            removable: false
    #            removable_title: 'Remove'
    #            solid: false
    #            use_footer: false
    #        button:
    #            type: 'primary'
    #            size: false

    routes:
        adminlte_welcome: admin_index
        adminlte_login: app_login
        adminlte_login_check: app_login
        adminlte_registration: app_register
        adminlte_password_reset: app_register
        adminlte_message: admin_index
        adminlte_messages: admin_index
        adminlte_notification: admin_index
        adminlte_notifications: admin_index
        adminlte_task: admin_index
        adminlte_tasks: admin_index
        adminlte_profile: admin_index