security:
    encoders:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        chain_provider:
            chain:
                providers:
                    - 'app_user_provider'
                    - 'discord_user_provider'

        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

        discord_user_provider:
            id: App\Security\DiscordUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            user_checker: App\Security\UserChecker
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\AppMainAuthenticator
                    - App\Security\DiscordAuthenticator
                entry_point: App\Security\AppMainAuthenticator
            logout:
                path: app_logout
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/profile, roles: ROLE_USER }
